name: CI

on: workflow_dispatch
inputs:
      code:
        description: 'OAuth Code'
        required: false
      pin:
        description: 'Six digit Pin'
        required: false

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setting Up CRD
      if: ${{ github.event.inputs.code }}
      run: ./setup.ps1
    - name: No OAuth detected Setting up Ngrok
      run: setup2.ps1
    - name: Authentication of Ngrok.io
      run: .\ngrok\ngrok.exe authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Started Ngrok
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
    - name: Download Timeout Script
      run: Invoke-WebRequest https://raw.githubusercontent.com/rameshchatarji/Windows-CRD/main/timeout.ps1 -OutFile timeout.ps1
    - name: Keep Alive
      continue-on-error: true
      run: ./timeout.ps1
    - name: Keep Alive
      continue-on-error: true
      run: ./timeout.ps1
    - name: Keep Alive
      continue-on-error: true
      run: ./timeout.ps1
    - name: Keep Alive
      continue-on-error: true
      run: ./timeout.ps1
