name: CI

on: 
  workflow_dispatch:
    inputs:
     code:
        description: 'OAuth Code'
     pin:
        description: 'Six digit Pin'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setting Up CRD
      if: ${{ github.event.inputs.code }}
      run: ./setup.ps1
    - name: OAuth with CRD
      if: ${{ github.event.inputs.code }}
      run: ${{ github.event.inputs.code }} ${{ github.event.inputs.pin }}
    - name: Download Run in Background Process
      run: Invoke-WebRequest https://raw.githubusercontent.com/AloneGuru/Alone-VM/main/alive.ps1 -OutFile alive.ps1
    - name: Running CRD in Background
      if: ${{ github.event.inputs.code }}
      run: ./alive.ps1
    - name: No OAuth detected Setting up Ngrok
      run: ./setup2.ps1
    - name: Authenticating Ngrok.io
      run: .\ngrok\ngrok.exe authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Started Ngrok
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
    - name: Running in Background
      run: ./alive.ps1
    - name: Running in Background
      run: ./alive.ps1
    - name: Running in Background
      run: ./alive.ps1
    - name: Running in Background
      run: ./alive.ps1
